# general
run_name: 'test'

# coding parameters
block_length: 20
channel_blocks: 1
code_length: 255
use_ecc: False

# channel
memory_length: 4
channel_type: 'ISI_AWGN' #'ISI_AWGN','Poisson'
noisy_est_var: 0 # 0, 0.1 for ISI_AWGN, 0.08 for Poisson

# gamma values
gamma_start: 0.1
gamma_end: 2
gamma_num: 10

# validation hyperparameters
val_minibatch_num: 5 # the more the merrier
val_minibatch_size: 20000 # the more the merrier
val_SNR_start: 8
val_SNR_end: 8
thresh_errors: 10000 # monte-carlo error threshold per point

# train hyperparameters
train_minibatch_num: 20
train_minibatch_size: 100 # should be big enough
train_SNR_start: 0
train_SNR_end: 1
lr: 0.001 # learning rate
loss_type: 'CrossEntropy' # 'BCE','CrossEntropy'

# seed
noise_seed: 345000
word_seed: 786000
