# general
run_name: 'tes4t'

# coding parameters
block_length: 10
channel_blocks: 1
code_length: 255
use_ecc: False

# channel
memory_length: 4
channel_type: 'ISI_AWGN' #'ISI_AWGN','Poisson'
noisy_est_var: 0 # 0, 0.1 for ISI_AWGN, 0.08 for Poisson

# gamma values
gamma_start: 1
gamma_end: 1
gamma_num: 1

# validation hyperparameters
val_minibatch_num: 5 # the more the merrier
val_minibatch_size: 20000 # the more the merrier
val_SNR_start: 8
val_SNR_end: 8

# train hyperparameters
train_minibatch_num: 1000
train_minibatch_size: 1000 # should be big enough
train_SNR_start: 8
train_SNR_end: 8
lr: 0.001 # learning rate
loss_type: 'CrossEntropy' # 'BCE','CrossEntropy','MSE'
print_every_n_train_minibatches: 50

# seed
noise_seed: 345000
word_seed: 786000
