# general
run_name: 'test'

# coding parameters
channel_blocks: 10
use_ecc: True

# channel
memory_length: 4
channel_type: 'ISI_AWGN' #'ISI_AWGN','Poisson'
noisy_est_var: 0 # 0, 0.1 for ISI_AWGN, 0.08 for Poisson
fading: True

# gamma values
gamma_start: 0.2
gamma_end: 0.2
gamma_num: 1

# validation hyperparameters
val_block_length: 1784
val_SNR_start: 6
val_SNR_end: 14
val_SNR_step: 2
val_words: 200

# train hyperparameters
train_block_length: 5000
train_minibatch_num: 100
train_minibatch_size: 16
train_SNR_start: 10
train_SNR_end: 10
train_SNR_step: 2
lr: 0.001 # learning rate
loss_type: 'CrossEntropy' # 'BCE','CrossEntropy','MSE'
print_every_n_train_minibatches: 5
optimizer_type: 'Adam' # 'Adam','RMSprop','SGD'
early_stopping_mode: 'on' # 'on', 'off'

# seed
noise_seed: 345000
word_seed: 786000

# classic Viterbi
fading_is_known: False