# general
run_name: 'original_vnet123'

# coding parameters
block_length: 1000
code_length: 255
use_ecc: False

# channel
memory_length: 4
channel_type: 'ISI_AWGN' #'ISI_AWGN','Poisson'
noisy_est_var: 0 # 0, 0.1 for ISI_AWGN, 0.08 for Poisson

# gamma values
gamma_start: 0.1
gamma_end: 2
gamma_num: 20

# validation hyperparameters
channel_blocks: 50 # the more the merrier
val_SNR_start: 8
val_SNR_end: 10

# train hyperparameters
train_minibatch_num: 500
train_minibatch_size: 32
train_SNR_start: 10
train_SNR_end: 10
lr: 0.001 # learning rate
loss_type: 'CrossEntropy' # 'BCE','CrossEntropy','MSE'
print_every_n_train_minibatches: 10
optimizer_type: 'Adam' # 'Adam','RMSprop','SGD'
early_stopping_mode: 'on' # 'on', 'off'

# seed
noise_seed: 345000
word_seed: 786000
