# general
run_name: 'self_supervised_viterbinet'

# coding parameters
channel_blocks: 10
use_ecc: True

# channel
memory_length: 4
channel_type: 'ISI_AWGN' #'ISI_AWGN','Poisson'
noisy_est_var: 0 # 0, 0.1 for ISI_AWGN, 0.08 for Poisson
fading_in_channel: True
fading_in_decoder: False

# gamma values
gamma_start: 0.2
gamma_end: 0.2
gamma_num: 1

# validation hyperparameters
val_block_length: 1784
val_SNR_start: 12
val_SNR_end: 12
val_SNR_step: 2
val_words: 50

# train hyperparameters
train_block_length: 5000
train_minibatch_num: 100
train_minibatch_size: 256
train_SNR_start: 6
train_SNR_end: 14
train_SNR_step: 2
lr: 0.0002 # learning rate
loss_type: 'CrossEntropy' # 'BCE','CrossEntropy','MSE'
print_every_n_train_minibatches: 10
optimizer_type: 'SGD' # 'Adam','RMSprop','SGD'
early_stopping_mode: 'on' # 'on', 'off'
self_supervised: True

# seed
noise_seed: 34500012
word_seed: 78600012

